### ISSUE TITLE
Nathanael should present webforms for editing metadata

### ISSUE THREAD

**Issue by ericpyle** [ubsicap/dbl.local.electron#19]
- [x] submit simple forms
- [x] submit factory forms
- [x] show errors in form (and show error icon in tree)
- [x] undo/save buttons for changed forms
- [x] add Review button to open metadata.xml
- [x] stick appbar to top (with open/close transition)
- [x] add name, language of entry to title bar
- [x] delete factory forms 
- [ ] show multiple errors across forms for partially filled metadata

**Comment by ericpyle** [comment]
@mvahowe @klassenjm starting to come together:

![image](https://user-images.githubusercontent.com/1125565/41626836-4c9f0d66-73e3-11e8-83da-83997fa35436.png)

**Comment by ericpyle** [comment]
@mvahowe @klassenjm Added "Details" when a step has a form as well as sub-forms

![image](https://user-images.githubusercontent.com/1125565/41798263-9c43699c-7632-11e8-9bb8-618fe9e04fe7.png)

**Comment by ericpyle** [comment]
@mvahowe @klassenjm 

Added support for "instances" of metadata already in the metadata.xml

![image](https://user-images.githubusercontent.com/1125565/41798338-ed98f47e-7632-11e8-91c6-ec6e85573218.png)

![image](https://user-images.githubusercontent.com/1125565/41798370-064aa0bc-7633-11e8-94ff-f8e543502769.png)

![image](https://user-images.githubusercontent.com/1125565/41798395-26517700-7633-11e8-81f6-b2552da5b598.png)

**Comment by ericpyle** [comment]
@mvahowe @klassenjm basic functionality is mostly finished now. mainly just need to add delete for instances of factory forms.

![image](https://user-images.githubusercontent.com/1125565/42579651-678faee8-84ee-11e8-9ab6-3bf3a507bcb9.png)

**Comment by klassenjm** [comment]
Looking good, @ericpyle . Do I need an update to DBL.Local to attempt to look at your latest version?

**Comment by ericpyle** [comment]
@klassenjm probably a good idea. However, it might be advisable to wait until another official Nathanael is released. Looking like next week.  Mark just hooked up a way to delete factory form intances. So I should add a button for that. Also, ideally we wouldn't allow editing metadata directly in a bundle without first creating a fork of it, but Mark hasn't implemented that yet for existing dbl entries.

**Comment by ericpyle** [comment]
I'm going to say this is 'complete' for now. Showing errors across multiple forms will make more since once I enable creating or forking metadata for new entries.

**Comment by mvahowe** [comment]
@ericpyle The functionality looks great! Design-wise, I would have expected that the trash can was for local name, not the entire country section. (I know it's sooo 1990 but I do think boxes helped here.) Could we move the add and remove buttons to the top of the section? Ideally, the add button would be outside (above) the section since it's not doing something to the section, and also because you presumably don't want multiple add buttons when there are already multiple sections.
