### ISSUE TITLE
Editing metadata forms while not in create mode

### ISSUE THREAD

**Issue by mvahowe** [ubsicap/dbl.local.electron#40]
To get into this state:

- fork a braille bundle from a text bundle (DBL Unit Test in this case)

- edit metadata, navigate straight to publications

- add a publication with just an id, hit save.

![not_create](https://user-images.githubusercontent.com/1576594/47820235-35da5c00-dd5d-11e8-8b53-0d1cb75c3ce4.png)

**Comment by ericpyle** [comment]
@mvahowe i'm have a difficult time reproducing this. I think I may know how to fix it, but if you reproduce it again, can you click in the Console on the right, and do "Save as" (notInCreateMode.log)

**Comment by ericpyle** [comment]
@mvahowe fixed in v.0.13.1+ so that I wait until we're in create mode before opening the edit dialog
