### ISSUE TITLE
Stuck in upload mode if createUpload fails

### ISSUE THREAD

**Issue by mvahowe** [ubsicap/dbl.local.electron#41]
Jake observed this problem a few days ago, but it was obfuscated because there was also an issue with DBL.Local's handling of local validation errors. I've now fixed that and I think these two screenshots show DBL.Local correctly returning to store mode because of bad metadata, while Nathanael remains in uploading "mode".

Should be easy to replicate - just fork a bundle and try to upload it without creating a publication.
![hung_upload1](https://user-images.githubusercontent.com/1576594/47853254-6ca48680-ddde-11e8-9b87-b5cc3c4bf45d.jpg)
![hung_upload2](https://user-images.githubusercontent.com/1576594/47853255-6ca48680-ddde-11e8-95e7-fdf651468aa8.jpg)

**Comment by ericpyle** [comment]
@mvahowe wrote:
> Should be easy to replicate - just fork a bundle and try to upload it without creating a publication.

Not sure how to do that in nate. I'm pretty sure I try hard not to allow the user to click on the Upload button unless they've added at least one resource to a new bundle

**Comment by mvahowe** [comment]
@ericpyle Try forking a bundle and adding a resource that doesn't match any wizard. I think that ought to leave you with invalid metadata. (Or you could hack the metadata manually - there are no checks on the publication section, for example.)

**Comment by ericpyle** [comment]
@mvahowe i hacked the metadata directly to reproduce it. thanks

**Comment by ericpyle** [comment]
fixed in v.0.13.1+
