### ISSUE TITLE
Alert user to new update

### ISSUE THREAD

**Issue by mvahowe** [ubsicap/dbl.local.electron#47]
In NL we managed to use Nathanael for quite a long time before I realised that we hadn't restarted after downloading the latest release. It looks to me like there's a fairly simple solution to this at

https://electronjs.org/docs/tutorial/updates

(which I hope is in English for you.) I was imagining something like a pop-up that says "Updated, please restart." I don't think it _has_ to force the user to do this, but I don't think it would be a disaster if it did.

**Comment by mvahowe** [comment]
@ericpyle Not that surprised, but hope springs eternal.

**Comment by ericpyle** [comment]
@mvahowe having to work through this error:

```
[09:08:17.007] updater error
renderer.js:34 [09:08:17.013] Error: Can not find Squirrel
    at AutoUpdater.emitError (C:\Users\PyleE\AppData\Local\Programs\nathanael\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:58:24)
    at AutoUpdater.checkForUpdates (C:\Users\PyleE\AppData\Local\Programs\nathanael\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:29:19)
    at Timeout.undefined.process.platform.f.includes.setInterval [as _onTimeout] (C:\Users\PyleE\AppData\Local\Programs\nathanael\resources\app.asar\webpack:\node_modules\update-electron-app\index.js:48:57)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by ericpyle** [comment]
@mvahowe that error is too obscure for my little brain. so I will go back to the original auto updater, and try to add code for it to display more UI

**Comment by ericpyle** [comment]
@mvahowe the boilerplate that I based my electron app is using the one I used originally https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/1912/commits/3f0a01cb90161c742dd45273f0e1ef2b8c7d83b5, so I should probably stick with that for compatibility

**Comment by ericpyle** [comment]
@mvahowe hope the new dialog works after I publish v.0.15.1

**Comment by ericpyle** [comment]
@mvahowe not the prettiest dialog, but it's something (in v.0.15.1)

![image](https://user-images.githubusercontent.com/1125565/48380923-4b298180-e69f-11e8-8ebd-8653717e2aa4.png)

**Comment by mvahowe** [comment]
@ericpyle That looks like an absolutely fine dialog to me!

**Comment by mvahowe** [comment]
(I'm not seeing it when upgrading from 0.14.something but presumably that's because I needed the update in order to get the dialog for the next update?)

**Comment by ericpyle** [comment]
@mvahowe yes, you won't see the dialog until the next update
