### ISSUE TITLE
Visual hang on download

### ISSUE THREAD

**Issue by mvahowe** [ubsicap/dbl.local.electron#52]
The GUI gets stuck on 50% download while the console shows global_status of 0,0 and the bundle being restored to store mode.

The easiest way to avoid this entire class of issue would be to expose the mode of the bundle in the UX, ie the UX says "downloading" when the mode is "download".

[half_a_download.log](https://github.com/ubsicap/dbl.local.electron/files/2562722/half_a_download.log)
![half_a_download](https://user-images.githubusercontent.com/1576594/48214521-697e3d00-e380-11e8-849c-531a29613059.png)

**Comment by ericpyle** [comment]
fixed in v.0.14.1
