### ISSUE TITLE
As a user I'd like to save my downloaded bundle resources to a folder

### ISSUE THREAD

**Issue by ericpyle** [ubsicap/dbl.local.electron#6]
- [x] download resources to selected folder
- [x] remember selected folder for next Saved To, or use Downloads
- [ ] persist savedTo folders after closing/app
- [x] integrate into bundle status
- [x] integrate into displayAs / search and filtering logic
- [x] make progress bar with transitions

**Comment by ericpyle** [comment]
Added Open in Folder after user selects folder to save to.

![image](https://user-images.githubusercontent.com/1125565/40146314-a85ead4c-592a-11e8-9838-5023a7db6348.png)

**Comment by ericpyle** [comment]
Changed the progress bar to use material design component (with animation)

![image](https://user-images.githubusercontent.com/1125565/40214321-a83a8d0e-5a1f-11e8-9359-4f0c4a4e4718.png)

**Comment by klassenjm** [comment]
This is looking really nice, @ericpyle

**Comment by ericpyle** [comment]
I'm not going to bother persisting saveTo folders for now
